### ISSUE TITLE
Pelvis Reset Key Causes Error When Using Manual Bone Selection

### ISSUE THREAD

**Issue by Zedimation** [penolakushari/RagdollMover#1]
Pressing the reload key to reset the selection gizmo location whilst a non-physics bone is selected causes:

[ragdollmover-checking] addons/ragdollmover-checking/lua/entities/rgm_axis/init.lua:202: bad argument # 1 to 'SetAngles' (Angle expected, got nil)
    1. SetAngles - [C]:-1
        2. unknown - addons/ragdollmover-checking/lua/entities/rgm_axis/init.lua:202

It doesn't break anything with the tool, though it will look alerting to those will little knowledge on the matter. Reselecting another bone fixes the issue. Possible solution to make a secondary function for the Reload key when the "Manual Bone Picking" function is enabled, such as moving the selection gizmo to the selected BoneID, which could also be beneficial for props/ragdolls with non-accessible bones other than the pelvis.

**Comment by penolakushari** [comment]
Sounds like a good idea. Although I was thinking to make it so when you select different BoneID it'll get to it automatically without even needing to click on the ragdoll you've selected. Seems like problem lies in the fact that I completely didn't touch the reload function, and didn't make it update variable that the bone we set with reload key is physics one, oops.

**Comment by penolakushari** [comment]
Fixed with https://github.com/penolakushari/RagdollMover/commit/c03028da2c7155717bffb76bf3d3fb33669c700e
